# Generated by Django 2.2 on 2020-03-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='workers',
            field=models.ManyToManyField(related_name='jobs_worked', to='exam_app.User'),
        ),
    ]
